version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: genomewiz
    ports: ["5432:5432"]
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/genomewiz
    volumes: [".:/code"]
    depends_on: [db]
    ports: ["8000:8000"]
